version: '2'

services:
  # docker-compose pull
  # ./bin/dev/docker-compose run --rm rails /bin/bash # then > ./bin/dev/init_tmux_session
  # ./bin/dev/docker-compose run --rm rails ./bin/dev/init_tmux_session
  # ./bin/dev/docker-compose ps
  pg:
    # .docker-compose up -d pg
    image: postgres:9.3.12
    expose:
      - 5432
    ports:
      - 5432
    volumes:
      - /var/docker/golang-crud-example/pg/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    logging:
      options:
        max-size: '50m'
